/*
 * protocolos.h
 *
 *  Created on: 28/9/2017
 *      Author: utnso
 */

#ifndef PROTOCOLOS_H_
#define PROTOCOLOS_H_

typedef enum {
	CONEXION_EXITOSA = 1, //Esto tiene el fin de reemplazar el "Todo ok papa..."
	HANDSHAKE,
	DESCONEXION_INMINENTE,

	//ESI - PLANIFICADOR
	EJECUTAR_SENTENCIA,
	FINALIZAR_PROCESO,
	FALLO_EN_EJECUCION,

	//ESI - COORDINADOR
	GET,
	SET,
	STORE,
	ERROR_TAMANIO_CLAVE,
	ERROR_CLAVE_NO_IDENTIFICADA,
	ERROR_DE_COMUNICACION,
	ERROR_CLAVE_INEXISTENTE,

	//ESI GENERAL
	EJECUCION_EXITOSA,

	//COORDINADOR - INSTANCIA
	CONFIGURACION_ENTRADAS
} t_protocolo;


typedef enum {
	ESI,
	PLANIFICADOR,
	COORDINADOR,
	INSTANCIA

} t_proceso;


#endif /* PROTOCOLOS_H_ */
